const dummyBudgetData = [
  {
    id: "a1",
    name: "Project Alpha",
    description: "Development of the Alpha project.",
    total_hours: 150,
    tags: ["development", "alpha"],
    status: "active",
    start_date: "2023-01-01",
    end_date: "2023-06-30",
    timerange: "monthly",
  },
  {
    id: "a2",
    name: "Project Beta",
    description:
      "Research and development for Beta. This project focuses on exploring new technologies and methodologies to improve the efficiency and effectiveness of our processes. It includes extensive research, prototyping, and testing to validate the feasibility of the proposed solutions.",
    total_hours: 200,
    tags: ["research", "beta"],
    status: "completed",
    start_date: "2022-01-01",
    end_date: "2022-12-31",
    timerange: "quarterly",
  },
  {
    id: "a3",
    name: "Project Gamma",
    description:
      "Marketing campaign for Gamma. The campaign aims to increase brand awareness and drive sales through various marketing channels including social media, email marketing, and content marketing. It involves creating and executing a comprehensive marketing strategy.",
    total_hours: 100,
    tags: ["marketing", "gamma"],
    status: "active",
    start_date: "2023-03-01",
    end_date: "2023-09-30",
    timerange: "weekly",
  },
  {
    id: "a4",
    name: "Project Delta",
    description:
      "Customer support for Delta. This project focuses on providing exceptional customer service and support to our clients. It includes setting up a support system, training support staff, and implementing processes to ensure timely and effective resolution of customer issues.",
    total_hours: 80,
    tags: ["support", "delta"],
    status: "pending",
    start_date: "2023-05-01",
    end_date: "2023-11-30",
    timerange: "monthly",
  },
  {
    id: "a5",
    name: "Project Epsilon",
    description:
      "Design phase for Epsilon. This project involves creating detailed design specifications and prototypes for the Epsilon project. It includes user research, wireframing, and creating high-fidelity designs that align with the project requirements and user needs.",
    total_hours: 120,
    tags: ["design", "epsilon"],
    status: "active",
    start_date: "2023-02-01",
    end_date: "2023-08-31",
    timerange: "bi-weekly",
  },
  {
    id: "a6",
    name: "Project Zeta",
    description:
      "Implementation of Zeta features. This project focuses on developing and implementing new features for the Zeta application. It includes coding, testing, and deploying the features to ensure they meet the specified requirements and provide a seamless user experience.",
    total_hours: 180,
    tags: ["implementation", "zeta"],
    status: "completed",
    start_date: "2022-04-01",
    end_date: "2022-10-31",
    timerange: "monthly",
  },
  {
    id: "a7",
    name: "Project Eta",
    description:
      "Testing and QA for Eta. This project involves conducting thorough testing and quality assurance for the Eta application. It includes creating test plans, executing test cases, and identifying and resolving any issues to ensure the application meets the highest quality standards.",
    total_hours: 90,
    tags: ["testing", "eta"],
    status: "active",
    start_date: "2023-06-01",
    end_date: "2023-12-31",
    timerange: "quarterly",
  },
  {
    id: "a8",
    name: "Project Theta",
    description:
      "Deployment of Theta. This project focuses on deploying the Theta application to the production environment. It includes setting up the infrastructure, configuring the application, and ensuring a smooth and successful deployment with minimal downtime.",
    total_hours: 110,
    tags: ["deployment", "theta"],
    status: "pending",
    start_date: "2023-07-01",
    end_date: "2023-12-31",
    timerange: "monthly",
  },
  {
    id: "a9",
    name: "Project Iota",
    description:
      "Maintenance for Iota. This project involves ongoing maintenance and support for the Iota application. It includes monitoring the application, identifying and resolving any issues, and implementing updates and improvements to ensure the application remains stable and secure.",
    total_hours: 70,
    tags: ["maintenance", "iota"],
    status: "active",
    start_date: "2023-01-01",
    end_date: "2023-06-30",
    timerange: "weekly",
  },
  {
    id: "a10",
    name: "Project Kappa",
    description:
      "Research for Kappa. This project focuses on conducting research to explore new opportunities and innovations for the Kappa application. It includes gathering and analyzing data, identifying trends and insights, and developing recommendations for future development.",
    total_hours: 140,
    tags: ["research", "kappa"],
    status: "completed",
    start_date: "2022-03-01",
    end_date: "2022-09-30",
    timerange: "bi-weekly",
  },
  // Duplicated and modified items
  {
    id: "a11",
    name: "Project Lambda",
    description: "Development of the Lambda project.",
    total_hours: 150,
    tags: ["development", "lambda"],
    status: "active",
    start_date: "2023-01-01",
    end_date: "2023-06-30",
    timerange: "monthly",
  },
  {
    id: "a12",
    name: "Project Mu",
    description:
      "Research and development for Mu. This project focuses on exploring new technologies and methodologies to improve the efficiency and effectiveness of our processes. It includes extensive research, prototyping, and testing to validate the feasibility of the proposed solutions.",
    total_hours: 200,
    tags: ["research", "mu"],
    status: "completed",
    start_date: "2022-01-01",
    end_date: "2022-12-31",
    timerange: "quarterly",
  },
  {
    id: "a13",
    name: "Project Nu",
    description:
      "Marketing campaign for Nu. The campaign aims to increase brand awareness and drive sales through various marketing channels including social media, email marketing, and content marketing. It involves creating and executing a comprehensive marketing strategy.",
    total_hours: 100,
    tags: ["marketing", "nu"],
    status: "active",
    start_date: "2023-03-01",
    end_date: "2023-09-30",
    timerange: "weekly",
  },
  {
    id: "a14",
    name: "Project Xi",
    description:
      "Customer support for Xi. This project focuses on providing exceptional customer service and support to our clients. It includes setting up a support system, training support staff, and implementing processes to ensure timely and effective resolution of customer issues.",
    total_hours: 80,
    tags: ["support", "xi"],
    status: "pending",
    start_date: "2023-05-01",
    end_date: "2023-11-30",
    timerange: "monthly",
  },
  {
    id: "a15",
    name: "Project Omicron",
    description:
      "Design phase for Omicron. This project involves creating detailed design specifications and prototypes for the Omicron project. It includes user research, wireframing, and creating high-fidelity designs that align with the project requirements and user needs.",
    total_hours: 120,
    tags: ["design", "omicron"],
    status: "active",
    start_date: "2023-02-01",
    end_date: "2023-08-31",
    timerange: "bi-weekly",
  },
  {
    id: "a16",
    name: "Project Pi",
    description:
      "Implementation of Pi features. This project focuses on developing and implementing new features for the Pi application. It includes coding, testing, and deploying the features to ensure they meet the specified requirements and provide a seamless user experience.",
    total_hours: 180,
    tags: ["implementation", "pi"],
    status: "completed",
    start_date: "2022-04-01",
    end_date: "2022-10-31",
    timerange: "monthly",
  },
  {
    id: "a17",
    name: "Project Rho",
    description:
      "Testing and QA for Rho. This project involves conducting thorough testing and quality assurance for the Rho application. It includes creating test plans, executing test cases, and identifying and resolving any issues to ensure the application meets the highest quality standards.",
    total_hours: 90,
    tags: ["testing", "rho"],
    status: "active",
    start_date: "2023-06-01",
    end_date: "2023-12-31",
    timerange: "quarterly",
  },
  {
    id: "a18",
    name: "Operation Sigma",
    description:
      "Deployment of Sigma. This project focuses on deploying the Sigma application to the production environment. It includes setting up the infrastructure, configuring the application, and ensuring a smooth and successful deployment with minimal downtime.",
    total_hours: 110,
    tags: ["deployment", "sigma"],
    status: "pending",
    start_date: "2023-07-01",
    end_date: "2023-12-31",
    timerange: "monthly",
  },
  {
    id: "a19",
    name: "Project Tau",
    description:
      "Maintenance for Tau. This project involves ongoing maintenance and support for the Tau application. It includes monitoring the application, identifying and resolving any issues, and implementing updates and improvements to ensure the application remains stable and secure.",
    total_hours: 70,
    tags: ["maintenance", "tau"],
    status: "active",
    start_date: "2023-01-01",
    end_date: "2023-06-30",
    timerange: "weekly",
  },
  {
    id: "a20",
    name: "Operation Upsilon",
    description:
      "Research for Upsilon. This project focuses on conducting research to explore new opportunities and innovations for the Upsilon application. It includes gathering and analyzing data, identifying trends and insights, and developing recommendations for future development.",
    total_hours: 140,
    tags: ["research", "upsilon"],
    status: "completed",
    start_date: "2022-03-01",
    end_date: "2022-09-30",
    timerange: "bi-weekly",
  },
  // Add more items as needed to reach 50
];

export default dummyBudgetData;
